### PR TITLE
docs: Prettify table as markdown

### PR DESCRIPTION
**Pull request by MichaelCurrin**
Using a markdown table for a much shorter and simpler table.

Also updated the wording.

### CODE REVIEW

**Comment by MichaelCurrin** [comment]
Also the backticks in markdown were not getting evaluated inside HTML but were as literal characters.

If you stick to HTML, you could have used HTML for that like so.

```diff
-<td>`DEPLOY_TOKEN`</td>
+<td><code>DEPLOY_TOKEN</code></td>
``` 

But that doesn't matter if you use markdown for the table like

```md
Field | Description
---   | ---
`DEPLOY_TOKEN` | PAT
```

**Comment by joaquimsn** [comment]
@MichaelCurrin The reason for using html tables instead of markdown was because jekyll's parse was breaking the tables into markdown when converted to html, to be used on Github pages

**Comment by MichaelCurrin** [comment]
Oh that's weird. I find markdown tables work fine on Jekyll sites

**Comment by MichaelCurrin** [comment]
See #7 then for HTML table with backtick fixes.

**Comment by joaquimsn** [comment]
On this page the tables were broken because they were large tables.

https://dp6.github.io/Marketing-Attribution-Models/

I will accept this PR to test

**Pull request merged**
